// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package store

import (
	"time"
)

type User struct {
	ID         string
	Username   string
	Password   string
	CreateTime time.Time
	UpdateTime time.Time
}
